# -*- coding: utf-8 -*-
"""IITT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWhZhnYHf4qbdFfBSlzQNc9RtNK-QQDh
"""

import zipfile

with zipfile.ZipFile("dataset.zip", 'r') as zip_ref:
    zip_ref.extractall()

print("Unzipped successfully")

from glob import glob

image_paths = sorted(glob("data/train/tiles/*.tif"))

print("Images:", len(image_paths))

def load_mask_from_image(img):
    gray = cv2.cvtColor((img*255).astype(np.uint8), cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 50, 150)
    edges = cv2.resize(edges, (256,256))
    edges = edges / 255.0
    return np.expand_dims(edges, -1)

import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras import layers, Model

def dice_loss(y_true, y_pred):
    smooth = 1e-6
    y_true_f = tf.reshape(y_true, [-1])
    y_pred_f = tf.reshape(y_pred, [-1])
    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return 1 - (2. * intersection + smooth) / (
        tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + smooth
    )

bce = tf.keras.losses.BinaryCrossentropy()

def combined_loss(y_true, y_pred):
    return bce(y_true, y_pred) + dice_loss(y_true, y_pred)



IMG_SIZE = 256

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

def load_image(path):
    img = cv2.imread(path)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    return img / 255.0

def load_mask_from_image(img):
    gray = cv2.cvtColor((img*255).astype(np.uint8), cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 50, 150)
    edges = cv2.resize(edges, (256,256))
    edges = edges / 255.0
    return np.expand_dims(edges, -1)


X = []
Y = []

for p in image_paths:
    img = load_image(p)
    mask = load_mask_from_image(img)   # 🔥 aligned mask

    X.append(img)
    Y.append(mask)

X = np.array(X)
Y = np.array(Y)

filtered_X = []
filtered_Y = []

for x, y in zip(X, Y):
    if np.sum(y) > 100:   # keep meaningful masks
        filtered_X.append(x)
        filtered_Y.append(y)

X = np.array(filtered_X)
Y = np.array(filtered_Y)

print("After filtering:", X.shape, Y.shape)

# split
split = int(0.8 * len(X))
X_train, X_val = X[:split], X[split:]
Y_train, Y_val = Y[:split], Y[split:]

# UNET
def build_unet():
    inputs = layers.Input((256,256,3))

    c1 = layers.Conv2D(16,3,activation='relu',padding='same')(inputs)
    p1 = layers.MaxPooling2D()(c1)

    c2 = layers.Conv2D(32,3,activation='relu',padding='same')(p1)
    p2 = layers.MaxPooling2D()(c2)

    c3 = layers.Conv2D(64,3,activation='relu',padding='same')(p2)

    u1 = layers.UpSampling2D()(c3)
    c4 = layers.Conv2D(32,3,activation='relu',padding='same')(u1)

    u2 = layers.UpSampling2D()(c4)
    c5 = layers.Conv2D(16,3,activation='relu',padding='same')(u2)

    outputs = layers.Conv2D(1,1,activation='sigmoid')(c5)

    return Model(inputs, outputs)

model = build_unet()


model.compile(
    optimizer='adam',
    loss=combined_loss,
    metrics=['accuracy']
)

model.summary()

model.fit(
    X_train, Y_train,
    validation_data=(X_val, Y_val),
    epochs=50,
    batch_size=4,
    callbacks=[early_stop]
)

model.save("unet_model.h5")

pred = model.predict(X_val)
pred = (pred > 0.2).astype(np.float32)

kernel = np.ones((5,5), np.uint8)

pred_processed = []

for p in pred:
    p = p.squeeze()

    # 🔥 STEP 1: threshold
    p = (p > 0.3).astype(np.uint8)

    # 🔥 STEP 2: blur (YOU ADD HERE)
    p = cv2.GaussianBlur(p.astype(np.float32), (3,3), 0)

    # 🔥 STEP 3: threshold again (VERY IMPORTANT)
    p = (p > 0.2).astype(np.uint8)

    # 🔥 STEP 4: morphology
    p = cv2.morphologyEx(p, cv2.MORPH_CLOSE, kernel)

    p = cv2.dilate(p, kernel, iterations=1)

    pred_processed.append(np.expand_dims(p, -1))

pred_processed = np.array(pred_processed)

import matplotlib.pyplot as plt

idx = 2

img = X_val[idx]
gt = Y_val[idx].squeeze()
pr = pred_processed[idx].squeeze()

# Create colored overlay
overlay = img.copy()

# Red for prediction
overlay[pr == 1] = [1, 0, 0]

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original Image")

plt.subplot(1,3,2)
plt.imshow(gt, cmap='gray')
plt.title("Ground Truth")

plt.subplot(1,3,3)
plt.imshow(overlay)
plt.title("Prediction Overlay (Red)")

plt.show()

diff = np.zeros_like(gt)

# True Positive → White
diff[(gt==1) & (pr==1)] = 1

# False Positive → Gray
diff[(gt==0) & (pr==1)] = 0.5

# False Negative → Dark
diff[(gt==1) & (pr==0)] = 0.2

plt.imshow(diff, cmap='gray')
plt.title("Difference Map")
plt.colorbar()
plt.show()

plt.figure(figsize=(18,5))

plt.subplot(1,4,1)
plt.imshow(img)
plt.title("Image")

plt.subplot(1,4,2)
plt.imshow(gt, cmap='gray')
plt.title("Ground Truth")

plt.subplot(1,4,3)
plt.imshow(pr, cmap='gray')
plt.title("Prediction")

plt.subplot(1,4,4)
plt.imshow(overlay)
plt.title("Overlay")

plt.show()

plt.suptitle("Geospatial Feature Segmentation using U-Net", fontsize=16)

for i in range(3):
    plt.imshow(pred_processed[i].squeeze(), cmap='gray')
    plt.title(f"Sample {i}")
    plt.show()

pred = (pred > 0.6).astype(np.float32)   # increase threshold
